MERGE INTO v5_sysTranslation AS Target 

USING (VALUES 

   /* AUTH */
   ('pt-BR', 'TITLE_AUTH_LOGIN', 'Acesso ao Sistema'),
   ('pt-BR', 'TITLE_AUTH_REGISTER', 'Registro de Acesso'),
   ('pt-BR', 'TITLE_AUTH_PASSWORD', 'Atualizar Senha'),
   ('pt-BR', 'TITLE_AUTH_REGISTER_RESULT', 'Bem-vindo'),
   ('pt-BR', 'MENU_AUTH_PASSWORD', 'Atualizar Senha'),
   ('pt-BR', 'MENU_AUTH_LOGOUT', 'Sair'),
   ('pt-BR', 'LABEL_AUTH_EMAIL', 'Email'),
   ('pt-BR', 'LABEL_AUTH_FULLNAME', 'Nome'),
   ('pt-BR', 'LABEL_AUTH_USERNAME', 'Email'),
   ('pt-BR', 'LABEL_AUTH_PASSWORD', 'Senha'),
   ('pt-BR', 'LABEL_AUTH_PASSWORD_CURRENT', 'Senha Atual'),
   ('pt-BR', 'LABEL_AUTH_PASSWORD_NEW', 'Nova Senha'),
   ('pt-BR', 'LABEL_AUTH_PASSWORD_CONFIRMATION', 'Confirme a Senha'),
   ('pt-BR', 'LABEL_AUTH_ROLE', 'Perfil'),
   ('pt-BR', 'LABEL_AUTH_ISPERSISTENT', 'Manter-me conectado'),
   ('pt-BR', 'LABEL_AUTH_NOT_ISACTIVEUSER', 'Usuário desabilitado'),
   ('pt-BR', 'MSG_AUTH_EMAIL_REQUIRED', 'Informe seu email'),
   ('pt-BR', 'MSG_AUTH_USERNAME_REQUIRED', 'Informe seu email de acesso'),
   ('pt-BR', 'MSG_AUTH_FULLNAME_REQUIRED', 'Informe seu nome'),
   ('pt-BR', 'MSG_AUTH_PASSWORD_REQUIRED', 'Informe sua senha'),
   ('pt-BR', 'MSG_AUTH_PASSWORD_CURRENT_REQUIRED', 'Informe sua senha atual'),
   ('pt-BR', 'MSG_AUTH_PASSWORD_NEW_REQUIRED', 'Informe sua nova senha'),
   ('pt-BR', 'MSG_AUTH_PASSWORD_CONFIRMATION_REQUIRED', 'Confirme sua senha'),
   ('pt-BR', 'MSG_AUTH_ROLE_REQUIRED', 'Informe a descrição do perfil'),
   ('pt-BR', 'MSG_AUTH_EMAIL_INVALID', 'Informe um endereço de email válido'),
   ('pt-BR', 'MSG_AUTH_USERNAME_INVALID', 'Utilize ao menos 3 caracteres para seu usuário'),
   ('pt-BR', 'MSG_AUTH_PASSWORD_INVALID', 'Utilize ao menos 6 caracteres para sua senha contendo números, símbolos e letras'),
   ('pt-BR', 'MSG_AUTH_PASSWORD_CONFIRMATION_INVALID', 'Sua confirmação não bate com a senha'),
   ('pt-BR', 'MSG_AUTH_ROLE_INVALID', 'Utilize ao menos 2 caracteres para a descrição do perfil'),
   ('pt-BR', 'MSG_AUTH_INVALID_LOGIN', 'Autenticação inválida'),
   ('pt-BR', 'MSG_AUTH_REGISTER_RESULT', '<p>Enviamos uma mensagem para seu <b>email</b> com as instruções de <b>ativação</b> de sua conta.</p> <p>Faça a ativação para começar a usufruir do período de degustação <b>gratuíto</b>.</p> <p>Qualquer dúvida, entre em contato conosco.</p>'),
   ('pt-BR', 'LABEL_AUTH_LOGIN', 'Acessar'),
   ('pt-BR', 'LABEL_AUTH_REGISTER', 'Registar'),
   ('pt-BR', 'LINK_AUTH_REGISTER_RESULT_LOGIN', 'Acessar o sistema'),
   ('pt-BR', 'MSG_AUTH_LOGIN', 'Já possui acesso ao sistema? Clique aqui.'),
   ('pt-BR', 'MSG_AUTH_REGISTER', 'Ainda não possui acesso? Clique aqui.'),
   ('pt-BR', 'MSG_AUTH_RECOVER', 'Clique para recuperar sua senha'),
   ('pt-BR', 'TITLE_AUTH_REGISTER_ACTIVATE', 'Ativação de Acesso'),
   ('pt-BR', 'LABEL_AUTH_REGISTER_ACTIVATE', 'Resultado da Ativação'),
   ('pt-BR', 'LINK_AUTH_REGISTER_ACTIVATE_LOGIN', 'Entrar'),
   ('pt-BR', 'LINK_AUTH_REGISTER_ACTIVATE_REGISTER', 'Tentar novamente'),
   ('pt-BR', 'LABEL_AUTH_REGISTER_ACTIVATE_EMAIL_SUBJECT', 'FriendlyCashFlow: Ativação de Acesso'),
   ('pt-BR', 'LABEL_AUTH_REGISTER_ACTIVATE_EMAIL_BODY', 'Por favor, confirme sua conta clicando <a href={0}>aqui</a>.'),
   ('pt-BR', 'MSG_AUTH_REGISTER_ACTIVATE', 'Ativação efetuada com sucesso.'),
   ('pt-BR', 'TITLE_USERS_MAIN', 'Usuários'),
   ('pt-BR', 'LABEL_USERS_USERNAME', 'Usuário'),
   ('pt-BR', 'LABEL_USERS_FULLNAME', 'Nome'),
   ('pt-BR', 'LABEL_USERS_EMAIL', 'Email'),
   ('pt-BR', 'LABEL_USERS_EMAILCONFIRMED', 'Confirmado'),
   ('pt-BR', 'LABEL_USERS_JOINDATE', 'Criação'),
   ('pt-BR', 'LABEL_USERS_EXPIRATIONDATE', 'Expiração'),
   ('pt-BR', 'LABEL_USERSROLES_ADMIN', 'Admin'),
   ('pt-BR', 'LABEL_USERSROLES_USER', 'User'),
   ('pt-BR', 'LABEL_USERSROLES_VIEWER', 'Viewer'),
   ('pt-BR', 'TITLE_USERSSIGNATURE', 'Assinaturas'),
   ('pt-BR', 'LABEL_USERSSIGNATURE_ADD_MONTH', '+1 Mês'),
   ('pt-BR', 'LABEL_USERSSIGNATURE_ADD_YEAR', '+1 Ano'),
   ('pt-BR', 'MSG_USERSSIGNATURE_FOOTER_ALERT', 'Verifique sua assinatura'),

   /* ACCOUNT */
   ('pt-BR', 'TITLE_ACCOUNTS_MAIN', 'Contas'),
   ('pt-BR', 'TITLE_ACCOUNTS_MAIN_ACTIVE', 'Contas Ativas'),
   ('pt-BR', 'TITLE_ACCOUNTS_MAIN_ALL', 'Todas as Contas'),
   ('pt-BR', 'TITLE_ACCOUNTS_GENERAL', 'Geral'),
   ('pt-BR', 'TITLE_ACCOUNTS_BANK', 'Banco'),
   ('pt-BR', 'TITLE_ACCOUNTS_CREDITCARD', 'Cartão de Crédito'),
   ('pt-BR', 'TITLE_ACCOUNTS_INVESTMENT', 'Investimento'),
   ('pt-BR', 'TITLE_ACCOUNTS_SERVICE', 'Serviços'),
   ('pt-BR', 'LABEL_ACCOUNTS_IDACCOUNT', 'Conta'),
   ('pt-BR', 'LABEL_ACCOUNTS_TEXT', 'Descrição'),
   ('pt-BR', 'MSG_ACCOUNTS_TEXT_REQUIRED', 'Informe a descrição da conta'),
   ('pt-BR', 'MSG_ACCOUNTS_TEXT_MAXLENGTH', 'Utilize 500 caracteres ou menos para descrição'),
   ('pt-BR', 'MSG_ACCOUNTS_TEXT_DUPLICITY', 'Você já possui conta com essa descrição'),   
   ('pt-BR', 'MSG_ACCOUNTS_ACCOUNT_NOTFOUND', 'A conta não foi encontrada'),
   ('pt-BR', 'MSG_ACCOUNTS_ADD_NEW', 'Clique para adicionar uma conta'),
   ('pt-BR', 'LABEL_ACCOUNTS_TYPE', 'Tipo'),
   ('pt-BR', 'LABEL_ACCOUNTS_CLOSINGDAY', 'Dia de Fechamento'),
   ('pt-BR', 'LABEL_ACCOUNTS_DUEDAY', 'Dia de Vencimento'),
   ('pt-BR', 'LABEL_ACCOUNTS_ACTIVE', 'Ativa'),   
   ('pt-BR', 'ENUM_ACCOUNTTYPE_GENERAL', 'Geral'),
   ('pt-BR', 'ENUM_ACCOUNTTYPE_BANK', 'Banco'),
   ('pt-BR', 'ENUM_ACCOUNTTYPE_CREDITCARD', 'Cartão de Crédito'),
   ('pt-BR', 'ENUM_ACCOUNTTYPE_INVESTMENT', 'Investimento'),
   ('pt-BR', 'ENUM_ACCOUNTTYPE_SERVICE', 'Serviço'),

   /* CATEGORY */
   ('pt-BR', 'TITLE_CATEGORIES_MAIN', 'Categorias'),
   ('pt-BR', 'LABEL_CATEGORIES_INCOME', 'Receitas'),
   ('pt-BR', 'LABEL_CATEGORIES_EXPENSE', 'Despesas'),
   ('pt-BR', 'LABEL_CATEGORIES_IDCATEGORY', 'Categoria'),
   ('pt-BR', 'LABEL_CATEGORIES_TEXT', 'Descrição'),
   ('pt-BR', 'MSG_CATEGORIES_TEXT_REQUIRED', 'Informe a descrição da categoria'),
   ('pt-BR', 'MSG_CATEGORIES_TEXT_MAXLENGTH', 'Utilize 500 caracteres ou menos para descrição'),
   ('pt-BR', 'MSG_CATEGORIES_TEXT_DUPLICITY', 'Você já possui categoria com essa descrição'),   
   ('pt-BR', 'MSG_CATEGORIES_CATEGORY_NOTFOUND', 'A categoria não foi encontrada'),
   ('pt-BR', 'LABEL_CATEGORIES_TYPE', 'Tipo'),
   ('pt-BR', 'LABEL_CATEGORIES_PARENT', 'Categoria Pai'),
   ('pt-BR', 'ENUM_CATEGORYTYPE_NONE', 'Nenhum'),
   ('pt-BR', 'ENUM_CATEGORYTYPE_INCOME', 'Receita'),
   ('pt-BR', 'ENUM_CATEGORYTYPE_EXPENSE', 'Despesa'),
   ('pt-BR', 'ENUM_CATEGORYTYPE_TRANSFER', 'Transferência'),
   ('pt-BR', 'MSG_CATEGORIES_ADD_NEW', 'Clique para adicionar categorias'),

   /* ENTRY */
   ('pt-BR', 'TITLE_ENTRIES_MAIN', 'Lançamentos'),
   ('pt-BR', 'LABEL_ENTRIES_IDENTRY', 'Lançamento'),
   ('pt-BR', 'LABEL_ENTRIES_IDPATTERN', 'Descrição'),
   ('pt-BR', 'LABEL_ENTRIES_TEXT', 'Descrição'),
   ('pt-BR', 'LABEL_ENTRIES_TYPE', 'Tipo'),
   ('pt-BR', 'LABEL_ENTRIES_DUEDATE', 'Vencimento'),
   ('pt-BR', 'LABEL_ENTRIES_PAYDATE', 'Pagamento'),
   ('pt-BR', 'LABEL_ENTRIES_VALUE', 'Valor'),
   ('pt-BR', 'LABEL_ENTRIES_INITIAL_BALANCE', 'Saldo Inicial'),
   ('pt-BR', 'LABEL_ENTRIES_CURRENT_BALANCE', 'Saldo Atual'),
   ('pt-BR', 'LABEL_ENTRIES_OVERDUE_BALANCE', 'Lançamentos atrasados'),
   ('pt-BR', 'LABEL_ENTRIES_IDACCOUNTEXPENSE', 'Conta de Saída'),
   ('pt-BR', 'LABEL_ENTRIES_IDACCOUNTINCOME', 'Conta de Entrada'),
   ('pt-BR', 'LABEL_ENTRIES_FILTERACCOUNT_ALL', 'Todas as Contas'),
   ('pt-BR', 'LABEL_ACCOUNTS_FILTERDATE', 'Período'),
   ('pt-BR', 'MSG_ENTRIES_PAID', 'Pago'),
   ('pt-BR', 'MSG_ENTRIES_SORTING', 'Ordenação'),
   ('pt-BR', 'MSG_ENTRIES_IDCATEGORY_REQUIRED', 'Selecione a categoria do lançamento'),
   ('pt-BR', 'MSG_ENTRIES_IDACCOUNT_REQUIRED', 'Selecione a conta do lançamento'),
   ('pt-BR', 'MSG_ENTRIES_DUEDATE_REQUIRED', 'Informe a data de vencimento do lançamento'),
   ('pt-BR', 'MSG_ENTRIES_PAYDATE_REQUIRED', 'Informe a data de pagamento do lançamento'),
   ('pt-BR', 'MSG_ENTRIES_VALUE_REQUIRED', 'Informe o valor do lançamento'),
   ('pt-BR', 'MSG_ENTRIES_ENTRY_NOTFOUND', 'O lançamento não foi encontrado'),
   ('pt-BR', 'MSG_ENTRIES_ADD_NEW', 'Clique para adicionar lançamentos'),

   /* RECURRENCY */
   ('pt-BR', 'LABEL_RECURRENCIES_HASRECURRENCY', 'Repetição de parcelas para o lançamento'),
   ('pt-BR', 'LABEL_RECURRENCIES_TYPE', 'Frequencia'),
   ('pt-BR', 'ENUM_RECURRENCYTYPE_WEEKLY', 'Semanal'),
   ('pt-BR', 'ENUM_RECURRENCYTYPE_MONTHLY', 'Mensal'),
   ('pt-BR', 'ENUM_RECURRENCYTYPE_BIMONTHLY', 'Bimenstral'),
   ('pt-BR', 'ENUM_RECURRENCYTYPE_QUARTERLY', 'Trimestral'),
   ('pt-BR', 'ENUM_RECURRENCYTYPE_SEMIYEARLY', 'Semestral'),
   ('pt-BR', 'ENUM_RECURRENCYTYPE_YEARLY', 'Anual'),
   ('pt-BR', 'LABEL_RECURRENCIES_FIXED', 'Fixas'),
   ('pt-BR', 'LABEL_RECURRENCIES_QUANTITY', 'Qtde.Parcelas'),
   ('pt-BR', 'LABEL_RECURRENCIES_UPDATE', 'Aplicar as alterações'),
   ('pt-BR', 'ENUM_RECURRENCYUPDATE_CURRENT', 'Apenas na parcela atual'),
   ('pt-BR', 'ENUM_RECURRENCYUPDATE_FUTURES', 'Nesta e nas parcelas futuras'),
   ('pt-BR', 'MSG_RECURRENCIES_QUANTITY_REQUIRED', 'Informe a quantidade de parcelas'),

   /* CONFIGS */
   ('pt-BR', 'TITLE_CONFIGS_MAIN', 'Configurações'),
   ('pt-BR', 'TITLE_IMPORT', 'Importação de dados [beta]'),
   ('pt-BR', 'TITLE_USERS_REMOVEUSER', 'Excluir usuário'),
   ('pt-BR', 'MENU_CONFIGS', 'Configurações'),
   ('pt-BR', 'COMMAND_IMPORT', 'Importar'),
   ('pt-BR', 'COMMAND_REMOVEUSER', 'Excluir conta do usuário'),
   ('pt-BR', 'LABEL_IMPORTS_ACCOUNTS', 'Contas'),
   ('pt-BR', 'LABEL_IMPORTS_CATEGORIES', 'Categorias'),
   ('pt-BR', 'LABEL_IMPORTS_ENTRIES', 'Lançamentos'),
   ('pt-BR', 'LABEL_IMPORTS_STATE', 'Status'),
   ('pt-BR', 'LABEL_IMPORTS_DATE', 'Data'),
   ('pt-BR', 'TITLE_CONFIGS_DELETEUSERDATA', 'Apagar dados'),
   ('pt-BR', 'LABEL_CONFIGS_DELETEUSERDATA', 'Esse processo não poderá ser desfeito. Deseja realmente apagar todos os seus dados? '),
   ('pt-BR', 'COMMAND_CONFIGS_DELETEUSERDATA', 'Apagar todos os dados'),

   /* ANALYSIS */
   ('pt-BR', 'TITLE_ANALYSIS_MAIN', 'Análise de dados'),
   ('pt-BR', 'TITLE_ANALYSIS_DAILY_FLOW', 'Fluxo de despesas diárias'),
   ('pt-BR', 'LABEL_ANALYSIS_DAILY_FLOW_TODAY', 'Hoje'),
   ('pt-BR', 'TITLE_ANALYSIS_CATEGORY_EXPENSE_DETAILS', 'Distribuição das despesas'),
   ('pt-BR', 'TITLE_ANALYSIS_CATEGORY_INCOME_DETAILS', 'Distribuição das receitas'),
   ('pt-BR', 'TITLE_ANALYSIS_CATEGORY_GOAL', 'Meta das despesas'),
   ('pt-BR', 'LABEL_ANALYSIS_CATEGORY_GOAL', 'Meta'),
   ('pt-BR', 'TITLE_ANALYSIS_CATEGORY_TREND', 'Tendência das despesas nos últimos meses'),
   ('pt-BR', 'TITLE_ANALYSIS_BALANCE_TREND', 'Balanço nos últimos meses'),
   ('pt-BR', 'TITLE_ANALYSIS_BALANCE_LABEL', 'Balanço'),
   ('pt-BR', 'TITLE_ANALYSIS_CUMULATED_ENTRIES', 'Principais despesas acumuladas'),
   ('pt-BR', 'TITLE_ANALYSIS_DIMENSION_PATTERNS', 'Descrições'),
   ('pt-BR', 'TITLE_ANALYSIS_DIMENSION_PLANNED', 'Planejamento'),
   ('pt-BR', 'LABEL_ANALYSIS_DIMENSION_PLANNED', 'Planejado'),
   ('pt-BR', 'LABEL_ANALYSIS_DIMENSION_UNPLANNED', 'Não Planejado'),
   ('pt-BR', 'TITLE_ANALYSIS_DIMENSION_PAID', 'Situação'),
   ('pt-BR', 'LABEL_ANALYSIS_DIMENSION_PAID', 'Quitado'),
   ('pt-BR', 'LABEL_ANALYSIS_DIMENSION_UNPAID', 'Pendente'),
   ('pt-BR', 'LABEL_ANALYSIS_REMAINING_SUMMING', 'Soma dos Demais'),

    /* DASHBOARD */
   ('pt-BR', 'TITLE_DASHBOARD_MAIN', 'Painel'),
   ('pt-BR', 'TITLE_DASHBOARD_ACCOUNTS_BALANCE', 'Saldos das Contas'),
   ('pt-BR', 'TITLE_DASHBOARD_CATEGORIES_GOAL', 'Meta de Categorias'),
   ('pt-BR', 'TITLE_DASHBOARD_ENTRIES_OVERDUE', 'Lançamentos Vencidos'),
   ('pt-BR', 'TITLE_DASHBOARD_ENTRIES_NEXT', 'Vencendo nos Próximos Dias'),
   ('pt-BR', 'TITLE_DASHBOARD_ENTRIES_EMPTY', 'Nenhum Lançamento Vencendo'),

   /* BASE */
   ('pt-BR', 'MSG_BASE_EMPTY_LIST', 'Nenhum registro encontrado'),
   ('pt-BR', 'COMMAND_CONFIRM', 'Confirmar'),
   ('pt-BR', 'COMMAND_CANCEL', 'Cancelar'),
   ('pt-BR', 'COMMAND_REMOVE', 'Remover'),
   ('pt-BR', 'COMMAND_SAVE', 'Gravar')
) 
AS Source (idLanguage, idTranslation, Text) 

ON Target.idLanguage = Source.idLanguage And Target.idTranslation = Source.idTranslation

-- UPDATE 
WHEN MATCHED THEN UPDATE SET Text = Source.Text 

-- INSERT
WHEN NOT MATCHED BY TARGET THEN 
   INSERT (idLanguage, idTranslation, Text) 
   VALUES (idLanguage, idTranslation, Text) 

-- DELETE 
WHEN NOT MATCHED BY SOURCE THEN DELETE
;