name: Pull Request

on: [pull_request]

jobs:
  tests:
    name: Validate Changes
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Identity Backend - Build
        working-directory: 'sources/identity/api/'
        run: dotnet build

      - name: Identity Backend - Tests
        working-directory: 'sources/identity/api/'
        run: dotnet test /p:CoverletOutputFormat=lcov

      - name: Identity Backend - Report
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./sources/identity/api/coverage.info

      - name: Shared Frontend - Libraries
        working-directory: 'sources/shared/client/'
        run: npm install

      - name: Shared Frontend - Build
        working-directory: 'sources/shared/client/'
        run: npm run build

      - name: Identity Frontend - Libraries
        working-directory: 'sources/identity/client/'
        run: npm install

      - name: Identity Frontend - Build
        working-directory: 'sources/identity/client/'
        run: npm run build
