name: Pull Request

on: [pull_request]
  
jobs:
  tests:
    name: Validate Changes
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source
        uses: actions/checkout@v2
      
      - name: Build Project
        working-directory: 'sources/identity/api/'
        run: dotnet build
        
      - name: Run Tests
        working-directory: 'sources/identity/api/'
        run: dotnet test /p:CoverletOutputFormat=lcov

      - name: Write Report
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./sources/identity/api/lcov.info        
