name: Pull Request

on: [pull_request]

jobs:

  backend:
    name: Backend
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Identity - Restore
        working-directory: 'sources/identity/api/'
        run: dotnet restore

      - name: Identity - Build
        working-directory: 'sources/identity/api/'
        run: dotnet build --no-restore

      - name: Identity - Tests
        working-directory: 'sources/identity/api/'
        run: dotnet test --no-build /p:CoverletOutputFormat=lcov

      - name: Identity - Report
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./sources/identity/api/coverage.info

      - name: Application - Restore
        working-directory: 'sources/app/api/'
        run: dotnet restore

      - name: Application - Build
        working-directory: 'sources/app/api/'
        run: dotnet build --no-restore

  frontend:
    name: Frontend
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Restore
        working-directory: 'sources/frontend/'
        run: npm install

      - name: Shared - Build
        working-directory: 'sources/frontend/'
        run: npm run build ElesseShared

      - name: Identity - Build
        working-directory: 'sources/frontend/'
        run: npm run build ElesseIdentity

      - name: Shared - Build
        working-directory: 'sources/frontend/'
        run: npm run build ElesseCashFlow

