name: Pull Request

on: [pull_request]
  
jobs:
  tests:
    name: Validate Changes
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source
        uses: actions/checkout@v2
      
      - name: Build Project
        working-directory: 'sources/identity/api/'
        run: dotnet build
        
      - name: Run Tests
        working-directory: 'sources/identity/api/'
        run: dotnet test /p:CoverletOutputFormat=opencover
