name: Pull Request

on: [pull_request]

jobs:

  backend:
    name: Backend
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Identity - Restore
        working-directory: 'sources/backend/identity/'
        run: dotnet restore

      - name: Identity - Build
        working-directory: 'sources/backend/identity/'
        run: dotnet build --no-restore

      - name: Identity - Run Tests
        working-directory: 'sources/backend/identity/'
        run: dotnet test --no-build /p:CoverletOutputFormat=lcov

      - name: Identity - Store Tests
        uses: actions/upload-artifact@v1.0.0
        with:
          name: identity-tests
          path: ./sources/backend/identity/coverage.info

      # - name: Identity - Report
      #   uses: romeovs/lcov-reporter-action@v0.2.16
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     lcov-file: ./sources/backend/identity/coverage.info

      - name: Application - Restore
        working-directory: 'sources/backend/main/'
        run: dotnet restore

      - name: Application - Build
        working-directory: 'sources/backend/main/'
        run: dotnet build --no-restore

  frontend:
    name: Frontend
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Restore
        working-directory: 'sources/frontend/'
        run: npm install

      - name: Build
        working-directory: 'sources/frontend/'
        run: npm run build

      - name: Run Tests
        working-directory: 'sources/frontend/'
        run: npm run test

      - name: Store Tests
        uses: actions/upload-artifact@v1.0.0
        with:
          name: frontend-tests
          path: ./sources/frontend/coverage.info

  testReports:
    name: Test Reports
    runs-on: ubuntu-latest
    needs: [backend,frontend]

    steps:

      - name: Retrieve Reports
        uses: actions/download-artifact@v1.0.0
        with:
          path: testReports

      - name: List Reports
        run: ls -R
        working-directory: testReports
