name: Pull Request

on: [pull_request]
  
jobs:
  tests:
    name: Validate Changes
    runs-on: windows-latest

    steps:

      - name: Checkout Source
        uses: actions/checkout@v2
      
      - name: Build Project
        working-directory: 'sources/identity/api/'
        run: dotnet build
        
      - name: Run Tests
        working-directory: 'sources/identity/api/'
        run: dotnet test /p:CoverletOutputFormat=opencover

      # - name: Send Tests Report to Codecov.IO
      #   run: |
      #     curl -s https://codecov.io/bash | bash
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          