name: Pull Request

on: [ pull_request ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

      - name: Retrieve Sources
        uses: actions/checkout@v2

      - name: Frontend Dependecies
        working-directory: 'sources/Frontend'
        run: |
          npm install --no-save

      - name: Frontend Build
        working-directory: 'sources/Frontend'
        run: |
          npm run build

      - name: Backend Dependecies
        working-directory: 'sources'
        run: |
          dotnet restore

      - name: Backend Tests
        working-directory: 'sources'
        run: |
          #dotnet build --no-restore
          dotnet test /p:CoverletOutputFormat=opencover
