name: Release

on:
  push:
    branches: [ v7 ]
  # release:
  #   types: [created]

env:
  version: 7.0.${{ github.run_number }}

jobs:

  backend:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Clean
        # workaroud for environment with greater "5.0" version than the required "3.1"
        working-directory: 'sources/backend'
        run: |
          cd shared
          dotnet clean --configuration Release
          cd ../identity
          dotnet clean --configuration Release
          cd ../accounts
          dotnet clean --configuration Release
          cd ../categories
          dotnet clean --configuration Release
          cd ../patterns
          dotnet clean --configuration Release
          cd ../main
          dotnet clean --configuration Release

      - name: Version
        working-directory: 'sources/backend/main'
        run: |
          echo ${{ env.version }}
          sed -i 's|<Version>1.0.0</Version>|<Version>${{ env.version }}</Version>|g' main.csproj

      - name: Build Shared
        working-directory: 'sources/backend/shared'
        run: dotnet build --configuration Release

      - name: Build Identity
        working-directory: 'sources/backend/identity'
        run: dotnet build --configuration Release

      - name: Build Accounts
        working-directory: 'sources/backend/accounts'
        run: dotnet build --configuration Release

      - name: Build Categories
        working-directory: 'sources/backend/categories'
        run: dotnet build --configuration Release

      - name: Build Patterns
        working-directory: 'sources/backend/patterns'
        run: dotnet build --configuration Release

      - name: Build Main
        working-directory: 'sources/backend/main'
        run: dotnet build --configuration Release

      - name: Publish
        working-directory: 'sources/backend/main/'
        run: dotnet publish --no-build --no-restore --configuration Release --output ./publish

      - name: Store Packages
        uses: actions/upload-artifact@v2
        with:
          name: backend
          path: ./sources/backend/main/publish

  frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Version
        working-directory: 'sources/frontend'
        run: |
          echo ${{ env.version }}
          sed -i 's|"version": "1.0.0",|"version": "${{ env.version }}",|g' package.json
          sed -i 's|"version": "1.0.0",|"version": "${{ env.version }}",|g' src/manifest.webmanifest
        # cat src/manifest.webmanifest

      - name: Restore
        working-directory: 'sources/frontend'
        run: npm install

      - name: Build
        working-directory: 'sources/frontend'
        run: npm run build

      - name: Store Packages
        uses: actions/upload-artifact@v2
        with:
          name: frontend
          path: ./sources/frontend/dist/CashFlow

  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: [backend,frontend]

    steps:

      - name: Retrieve Packages
        uses: actions/download-artifact@v2
        with:
          path: ./publish

      - name: AppSettings Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: './publish/backend/appsettings.json,./publish/frontend/assets/appsettings.json'
        env:
          Frontend.Url: 'https://friendlycashflow.azurewebsites.net'
          Backend.Url: 'https://friendlycashflowapi.azurewebsites.net'
          Mongo.ConnStr: ${{ secrets.AZURE_BACKEND_MONGO_CONNSTR }}
          Mongo.Database: ${{ secrets.AZURE_BACKEND_MONGO_DATABASE }}
          Identity.PasswordSalt: ${{ secrets.AZURE_BACKEND_IDENTITY_PASSWORDSALT }}
          Identity.PasswordRules.MinimumUpperCases: 0
          Identity.PasswordRules.MinimumLowerCases: 0
          Identity.PasswordRules.MinimumNumbers: 0
          Identity.PasswordRules.MinimumSymbols: 0
          Identity.PasswordRules.MinimumSize: 5
          Identity.Token.SecuritySecret: ${{ secrets.AZURE_BACKEND_IDENTITY_TOKEN_SECURITYSECRET }}
          Identity.Token.Issuer: ${{ secrets.AZURE_BACKEND_IDENTITY_TOKEN_ISSUER }}
          Identity.Token.Audience: ${{ secrets.AZURE_BACKEND_IDENTITY_TOKEN_AUDIENCE }}
          Identity.Token.AccessExpirationInSeconds: 60
          Identity.Token.RefreshExpirationInSeconds: 3600
          AppInsights.Activated: true
          AppInsights.Key: ${{ secrets.AZURE_INSIGHTS_KEY }}
          AppInsights.GlobalProperties.Environment: PRD

      - name: Backend App
        uses: azure/webapps-deploy@v2
        with:
          app-name: friendlycashflowAPI
          publish-profile: ${{ secrets.AZURE_BACKEND_PUBLISH_PROFILE }}
          package: ./publish/backend

      - name: Frontend App
        uses: azure/webapps-deploy@v2
        with:
          app-name: friendlycashflow
          publish-profile: ${{ secrets.AZURE_FRONTEND_PUBLISH_PROFILE }}
          package: ./publish/frontend
